=== knti1012/swe/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    ADRESSE*,
    ARTIKEL*,
    KUNDE*,
    BESTELLUNG*,
    BESTELLPOSITION*,
    LIEFERUNG*,
    BESTELLUNG_LIEFERUNG*)>

<!ELEMENT ADRESSE EMPTY>
<!ATTLIST ADRESSE
    ID CDATA #REQUIRED
    LAND CDATA #REQUIRED
    STADT CDATA #REQUIRED
    STRASSE CDATA #REQUIRED
    HAUSNUMMER CDATA #REQUIRED
    PLZ CDATA #REQUIRED
>

<!ELEMENT ARTIKEL EMPTY>
<!ATTLIST ARTIKEL
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    GROESSE CDATA #REQUIRED
    FARBE CDATA #REQUIRED
    PREIS CDATA #IMPLIED
    ART CDATA #REQUIRED
    KATEGORIE CDATA #REQUIRED
    LAGERBESTAND CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT KUNDE EMPTY>
<!ATTLIST KUNDE
    ID CDATA #REQUIRED
    ADD_FK CDATA #REQUIRED
    NACHNAME CDATA #REQUIRED
    VORNAME CDATA #REQUIRED
    GESCHLECHT CDATA #REQUIRED
    EMAIL CDATA #REQUIRED
    PASSWORD CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG EMPTY>
<!ATTLIST BESTELLUNG
    ID CDATA #REQUIRED
    K_FK CDATA #REQUIRED
    PREIS CDATA #IMPLIED
    STATUS CDATA #REQUIRED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLPOSITION EMPTY>
<!ATTLIST BESTELLPOSITION
    ID CDATA #REQUIRED
    B_FK CDATA #REQUIRED
    AR_FK CDATA #REQUIRED
    ANZAHL CDATA #REQUIRED
    PREIS CDATA #IMPLIED
>

<!ELEMENT LIEFERUNG EMPTY>
<!ATTLIST LIEFERUNG
    ID CDATA #REQUIRED
    LIEFERANT CDATA #REQUIRED
    TRANSPORT_ART CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG_LIEFERUNG EMPTY>
<!ATTLIST BESTELLUNG_LIEFERUNG
    ID CDATA #REQUIRED
    B_FK CDATA #REQUIRED
    L_FK CDATA #REQUIRED
>

=== knti1012/swe/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <ADRESSE ID="1549191" LAND="Bulgarien" STADT="Sofia" STRASSE="Vitoshka" HAUSNUMMER="9" PLZ="1359"/>
  <ADRESSE ID="1733751" LAND="Frankreich" STADT="Paris" STRASSE="Jaque-rue" HAUSNUMMER="10" PLZ="63422"/>
  <ADRESSE ID="1870539" LAND="Deutschland" STADT="Naila" STRASSE="An Der Urania" HAUSNUMMER="9" PLZ="95119"/>
  <ADRESSE ID="2221186" LAND="Deutschland" STADT="Weiden" STRASSE="Koepenicker Str." HAUSNUMMER="59" PLZ="92619"/>
  <ADRESSE ID="2377676" LAND="Italien" STADT="Mailand" STRASSE="Piaza-San-Michelle" HAUSNUMMER="29" PLZ="94753"/>
  <ADRESSE ID="2429757" LAND="Deutschland" STADT="Berghaupten" STRASSE="Rankestrae" HAUSNUMMER="63" PLZ="77791"/>
  <ADRESSE ID="2580398" LAND="Spanien" STADT="Barcelona" STRASSE="Rainbow-Road" HAUSNUMMER="27" PLZ="12308"/>
  <ADRESSE ID="3174040" LAND="England" STADT="London" STRASSE="Jackson-Avenue" HAUSNUMMER="45" PLZ="11084"/>
  <ADRESSE ID="3256504" LAND="Deutschland" STADT="Waiblingen Hegnach" STRASSE="Kurfuerstenstrassee" HAUSNUMMER="46" PLZ="71334"/>
  <ADRESSE ID="3286139" LAND="Deutschland" STADT="Lningen" STRASSE="Genterstrasse" HAUSNUMMER="48" PLZ="49624"/>
  <ADRESSE ID="3375634" LAND="Deutschland" STADT="Holzkirchen" STRASSE="Gubener Str." HAUSNUMMER="33" PLZ="83607"/>
  <ADRESSE ID="3811389" LAND="Indonesien" STADT="Jakarta" STRASSE="Citragarden" HAUSNUMMER="49" PLZ="11840"/>
  <ADRESSE ID="3989932" LAND="Neuseeland" STADT="Wellington" STRASSE="John-Street" HAUSNUMMER="14" PLZ="8132"/>
  <ADRESSE ID="4412419" LAND="England" STADT="Manchester" STRASSE="Kingstreet" HAUSNUMMER="79" PLZ="72312"/>
  <ADRESSE ID="4749631" LAND="Deutschland" STADT="Aying" STRASSE="Jahnstrasse" HAUSNUMMER="39" PLZ="85653"/>
  <ADRESSE ID="5374507" LAND="Belgien" STADT="Bruessel" STRASSE="Vassili-Street" HAUSNUMMER="31" PLZ="3941"/>
  <ADRESSE ID="5403261" LAND="Kirgistan" STADT="Bishkek" STRASSE="Mischurina" HAUSNUMMER="207" PLZ="35272"/>
  <ADRESSE ID="5507120" LAND="Deutschland" STADT="Waldhof-Falkenstein" STRASSE="Guentzelstrasse" HAUSNUMMER="87" PLZ="54673"/>
  <ADRESSE ID="5789759" LAND="Frankreich" STADT="Lyon" STRASSE="Rue-de-Camembert" HAUSNUMMER="4" PLZ="83214"/>
  <ADRESSE ID="6140062" LAND="Deutschland" STADT="Hoya" STRASSE="Karl-Liebknecht-Strasse" HAUSNUMMER="70" PLZ="27318"/>
  <ADRESSE ID="6821566" LAND="Spanien" STADT="Madrid" STRASSE="Giuseppe-Street" HAUSNUMMER="27" PLZ="19243"/>
  <ARTIKEL ID="10001" NAME="t-s1" GROESSE="xxxl" FARBE="rot" PREIS="9.0" ART="maenner" KATEGORIE="t-shirt" LAGERBESTAND="100" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10002" NAME="wild" GROESSE="m" FARBE="pink" PREIS="4.0" ART="maenner" KATEGORIE="hose" LAGERBESTAND="200" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10003" NAME="sch2" GROESSE="36" FARBE="rosa" PREIS="13.0" ART="frauen" KATEGORIE="schuhe" LAGERBESTAND="30" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10004" NAME="rocket" GROESSE="xxl" FARBE="schwarz" PREIS="23.0" ART="frauen" KATEGORIE="unterwaesche" LAGERBESTAND="50" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10005" NAME="Ugly" GROESSE="120" FARBE="blau" PREIS="56.0" ART="frauen" KATEGORIE="schal" LAGERBESTAND="200" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10006" NAME="Casual" GROESSE="m" FARBE="gruen" PREIS="1.0" ART="frauen" KATEGORIE="top" LAGERBESTAND="30" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10007" NAME="Dirty" GROESSE="32-34" FARBE="blau" PREIS="34.0" ART="maenner" KATEGORIE="jeans" LAGERBESTAND="55" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10008" NAME="TipTop" GROESSE="s" FARBE="weiss" PREIS="3.0" ART="kinder" KATEGORIE="top" LAGERBESTAND="70" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10009" NAME="Sara" GROESSE="xs" FARBE="rot" PREIS="70.0" ART="frauen" KATEGORIE="kleid" LAGERBESTAND="30" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10010" NAME="Herbst" GROESSE="s" FARBE="schwarz" PREIS="60.0" ART="maenner" KATEGORIE="jacke" LAGERBESTAND="70" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10011" NAME="used" GROESSE="m" FARBE="braun" PREIS="120.0" ART="maenner" KATEGORIE="lederjacke" LAGERBESTAND="80" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10012" NAME="Enjoy" GROESSE="xs" FARBE="beige" PREIS="60.0" ART="kinder" KATEGORIE="mantel" LAGERBESTAND="300" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10013" NAME="Diesel" GROESSE="universal" FARBE="schwarz" PREIS="10.0" ART="unisex" KATEGORIE="brille" LAGERBESTAND="400" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10014" NAME="warm" GROESSE="36-39" FARBE="weiss" PREIS="12.0" ART="unisex" KATEGORIE="socken" LAGERBESTAND="205" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10015" NAME="bh11" GROESSE="75-c" FARBE="schwarz" PREIS="10.0" ART="frauen" KATEGORIE="bh" LAGERBESTAND="40" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10016" NAME="Swarowski" GROESSE="40" FARBE="silber" PREIS="15.0" ART="kinder" KATEGORIE="kette" LAGERBESTAND="11" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10017" NAME="RedBull" GROESSE="s" FARBE="blau" PREIS="17.0" ART="kinder" KATEGORIE="muetze" LAGERBESTAND="167" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10018" NAME="Mango" GROESSE="l" FARBE="braun" PREIS="13.0" ART="unisex" KATEGORIE="handschuhe" LAGERBESTAND="560" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10019" NAME="flipit" GROESSE="44" FARBE="lila" PREIS="5.0" ART="unisex" KATEGORIE="flip-flops" LAGERBESTAND="40" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10020" NAME="Gucci" GROESSE="xxl" FARBE="braun" PREIS="65.0" ART="frauen" KATEGORIE="tasche" LAGERBESTAND="35" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <ARTIKEL ID="10021" NAME="VRD" GROESSE="100" FARBE="schwarz" PREIS="11.0" ART="maenner" KATEGORIE="guertel" LAGERBESTAND="470" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <KUNDE ID="1405357" ADD_FK="2221186" NACHNAME="Feierabend" VORNAME="Marco" GESCHLECHT="M" EMAIL="MarcoFeierabend@mailinator.com" PASSWORD="234f55" ERZEUGT="2012-05-02 00:00:00.0" AKTUALISIERT="2012-07-09 00:00:00.0"/>
  <KUNDE ID="1430218" ADD_FK="2377676" NACHNAME="Freud" VORNAME="Philipp" GESCHLECHT="M" EMAIL="PhilippFreud@mailinator.com" PASSWORD="111" ERZEUGT="2012-05-10 00:00:00.0" AKTUALISIERT="2012-07-17 00:00:00.0"/>
  <KUNDE ID="1750839" ADD_FK="5403261" NACHNAME="Baumgartner" VORNAME="Jennifer" GESCHLECHT="W" EMAIL="JenniferBaumgartner@dodgit.com" PASSWORD="34f43t" ERZEUGT="2012-05-13 00:00:00.0" AKTUALISIERT="2012-07-20 00:00:00.0"/>
  <KUNDE ID="2239833" ADD_FK="6140062" NACHNAME="Drescher" VORNAME="Mandy" GESCHLECHT="W" EMAIL="MandyDrescher@spambob.com" PASSWORD="55231n" ERZEUGT="2012-05-01 00:00:00.0" AKTUALISIERT="2012-07-08 00:00:00.0"/>
  <KUNDE ID="2331175" ADD_FK="1870539" NACHNAME="Becker" VORNAME="Silke" GESCHLECHT="W" EMAIL="SilkeBecker@trashymail.com" PASSWORD="wad244" ERZEUGT="2012-05-17 00:00:00.0" AKTUALISIERT="2012-07-24 00:00:00.0"/>
  <KUNDE ID="2392668" ADD_FK="3174040" NACHNAME="Weiss" VORNAME="Gabriele" GESCHLECHT="W" EMAIL="GabrieleWeiss@spambob.com" PASSWORD="324h66" ERZEUGT="2012-05-09 00:00:00.0" AKTUALISIERT="2012-07-16 00:00:00.0"/>
  <KUNDE ID="2440155" ADD_FK="4749631" NACHNAME="Fuerst" VORNAME="Renz" GESCHLECHT="M" EMAIL="ReneFuerst@trashymail.com" PASSWORD="4tf5z53" ERZEUGT="2012-05-05 00:00:00.0" AKTUALISIERT="2012-07-12 00:00:00.0"/>
  <KUNDE ID="2516735" ADD_FK="1733751" NACHNAME="Friedman" VORNAME="Tanja" GESCHLECHT="W" EMAIL="TanjaFriedman@pookmail.com" PASSWORD="234f54t3" ERZEUGT="2012-05-20 00:00:00.0" AKTUALISIERT="2012-07-27 00:00:00.0"/>
  <KUNDE ID="2573153" ADD_FK="2429757" NACHNAME="Beckenbauer" VORNAME="Marie" GESCHLECHT="W" EMAIL="MarieBeckenbauer@pookmail.com" PASSWORD="231d3r" ERZEUGT="2012-05-18 00:00:00.0" AKTUALISIERT="2012-07-25 00:00:00.0"/>
  <KUNDE ID="2969638" ADD_FK="5374507" NACHNAME="Kirsch" VORNAME="Kevin" GESCHLECHT="M" EMAIL="KevinKirsch@spambob.com" PASSWORD="2cr34" ERZEUGT="2012-05-14 00:00:00.0" AKTUALISIERT="2012-07-22 00:00:00.0"/>
  <KUNDE ID="3534482" ADD_FK="5789759" NACHNAME="Kuhn" VORNAME="Kristin" GESCHLECHT="W" EMAIL="KristinKuhn@spambob.com" PASSWORD="12" ERZEUGT="2012-05-12 00:00:00.0" AKTUALISIERT="2012-07-19 00:00:00.0"/>
  <KUNDE ID="3604278" ADD_FK="6821566" NACHNAME="Zimmer" VORNAME="Janina" GESCHLECHT="W" EMAIL="JaninaZimmer@dodgit.com" PASSWORD="33g4552" ERZEUGT="2012-05-07 00:00:00.0" AKTUALISIERT="2012-07-14 00:00:00.0"/>
  <KUNDE ID="4473720" ADD_FK="3286139" NACHNAME="Decker" VORNAME="Lea" GESCHLECHT="W" EMAIL="LeaDecker@spambob.com" PASSWORD="sdawe" ERZEUGT="2012-05-16 00:00:00.0" AKTUALISIERT="2012-07-23 00:00:00.0"/>
  <KUNDE ID="4530709" ADD_FK="3989932" NACHNAME="Koertig" VORNAME="Stefan" GESCHLECHT="M" EMAIL="StefanKoertig@trashymail.com" PASSWORD="123f454" ERZEUGT="2012-05-19 00:00:00.0" AKTUALISIERT="2012-07-26 00:00:00.0"/>
  <KUNDE ID="4988806" ADD_FK="1549191" NACHNAME="Mueller" VORNAME="Antje" GESCHLECHT="W" EMAIL="AntjeMoller@pookmail.com" PASSWORD="34fggg4" ERZEUGT="2012-05-21 00:00:00.0" AKTUALISIERT="2012-07-28 00:00:00.0"/>
